ALTER DATABASE [C:\USERS\JOHAN\SOURCE\REPOS\DATABASETRIGGERPOC\DATABASETRIGGERPOC\DATA\SANDBOX.MDF] SET ENABLE_BROKER WITH ROLLBACK IMMEDIATE;

SELECT name, is_broker_enabled FROM sys.databases 


CREATE MESSAGE TYPE [EventMessage] VALIDATION = WELL_FORMED_XML

CREATE CONTRACT [EventContract] AUTHORIZATION dbo ([EventMessage] SENT BY INITIATOR);

CREATE QUEUE dbo.EventQueue WITH STATUS=ON

CREATE SERVICE EventService AUTHORIZATION dbo ON QUEUE dbo.EventQueue ([EventContract]); 